version: '3.3'
services:
  mysql:
    container_name: mysql
    image:  mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3336:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/mysql/_data:/var/lib/mysql
    restart: always
    networks:
      - red

  server:
    container_name: ticket-server
    image: ticket-server:latest
    ports:
      - "85:5000"
    environment:
      - PORT=5000
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_PORT=3306
      - DATABASE_URL=mysql
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - red
    restart: always

  client:
    container_name: ticket-client
    image: ticket-client:latest
    ports:
      - "86:6000"
    networks:
      - red
    restart: always

networks:
  red: